apiVersion: v1
kind: Service
metadata:
  name: log-parser
  namespace: log-namespace
  annotations:
    cloud.google.com/load-balancer-type: "External" # Instruct LB create External IP for Service
    cloud.google.com/l4-rbs: "enabled" # This annotation instructs GKE to create a backend service-based external passthrough Network Load Balancer that uses a regional backend service.
    cloud.google.com/backend-config: '{"default": "log-parser-backend"}' # Create Backend for Service
spec:
  type: LoadBalancer
  selector:
    app: log-parser
  ports:
    - name: tcp-logs
      protocol: TCP
      port: 5514
      targetPort: 8080
      nodePort: 30060 # Optional, define which exactly nodeport number will be used
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: 'log-parser-backend'
  namespace: log-namespace
